### PR TITLE
Add redis support

### PR DESCRIPTION
**Pull request by atul016**
Added redis support to instrument the code

### CODE REVIEW

**Comment by atul016** [comment]
@hekike Updated the pull request...

**Comment by hekike** [comment]
Cool, thanks! 

Sorry for the inconvenience, but one more step would be necessary, I moved the repository content to here:
https://github.com/RisingStack/opentracing-auto

`opentracing-auto` is the copy of this repository except that it's not Jaeger specific at all and supports multiple tracers parallel, my plan is that this library will be super thin and use `opentracing-auto` internally.

Do you want to move your commit there or should I copy the code?

**Comment by hekike** [comment]
Check this out to see how it would work: https://github.com/RisingStack/opentracing-auto/blob/master/example/server-pg.js

**Comment by atul016** [comment]
You can move the code.

**Comment by hekike** [comment]
@atul016 thanks for your contribution, your change landed here: https://github.com/RisingStack/opentracing-auto/commit/156c49b3549490d1a80ab270af88fe94d722a434

I'm closing this PR here.

**Pull request closed without merging**
