### PR TITLE
instrumentation of redis

### PR DESCRIPTION
**Pull request by atul016**
instrumentation of redis for jaeger client

### CODE REVIEW

**Comment by hekike** [comment]
Awesome, thanks for your contribution!

Please add the following changes before we release it:
- Could you please add the instrumentation to the README: https://github.com/RisingStack/jaeger-node#instrumentations 
- Please cover it with tests. See one of my latest commits https://github.com/RisingStack/jaeger-node/commit/83745028945f820c14acafb6ad0632f591174281

I'm happy to release it after that!

**Comment by hekike** [comment]
@atul016 do you need a help with this?

**Comment by atul016** [comment]
@hekike Done.. sry wasn't able to find time.

**Comment by hekike** [comment]
@atul016 thanks, please resolve conflicts, I cannot merge until that.

**Pull request closed without merging**
